### ISSUE TITLE
Release 1.5.1 not working with plone 4.3.19

### ISSUE THREAD

**Issue by ramiroluz** [collective/Products.windowZ#8]
To reproduce, installed from the bundle package.

https://launchpad.net/plone/4.3/4.3.19/+download/Plone-4.3.19-UnifiedInstaller.tgz

Add Products.WindowZ to the eggs section inside buildout.cfg

Add Products.WindowZ = 1.5.1 to the versions.cfg

Run bin/buildout and then, running bin/instance fg got this error:

```
File "$HOME/Plone/buildout-cache/eggs/Products.windowZ-1.5.1-py2.7.egg/Products/windowZ/upgrades.py", line 4, in <module>
    from plone import api
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "$HOME/Plone/zinstance/parts/instance/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "$HOME/Plone/buildout-cache/eggs/Products.windowZ-1.5.1-py2.7.egg/Products/windowZ/configure.zcml", line 9.2-9.34
    ZopeXMLConfigurationError: File "$HOME/Plone/buildout-cache/eggs/Products.windowZ-1.5.1-py2.7.egg/Products/windowZ/upgrades.zcml", line 8.2-16.8
    ImportError: cannot import name api

```

It works if the version is changed to 1.5 in the versions.cfg file.
Products.WindowZ = 1.5

**Comment by ramiroluz** [comment]
Adding plone.api to the dependencies in setup.py solved, but there are other problems,
some plone5 specific changes are not working in plone4, see #9.

This version is from the release 1.5.1, without plone.api yet:
https://github.com/collective/Products.windowZ/blob/c8c6c9541537cc943cfb8ac7f609c75e9d616eb2/setup.py
